version: "3.8"
services:
  mongodb:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: lim
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - data:/data/db

  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGO_INITDB_ROOT_USERNAME: lim
      MONGO_INITDB_ROOT_PASSWORD: secret
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

volumes:
  data:
  logs:
