name: Build and Deploy Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get short Git SHA
      id: git-version
      run: echo VERSION=$(git rev-parse --short=7 HEAD) >> $GITHUB_OUTPUT    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Normalize repo name
      run: |
        echo "OWN_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV      
    - name: Build and push Docker image frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ env.OWN_LOWER }}/${{ env.REPO_NAME }}:front-${{ steps.git-version.outputs.VERSION }}
    - name: Build and push Docker image backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ env.OWN_LOWER }}/${{ env.REPO_NAME }}:backend-${{ steps.git-version.outputs.VERSION }}

