name: Build and Deploy Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get short Git SHA
      id: git-version
      run: echo VERSION=$(git rev-parse --short=7 HEAD) >> $GITHUB_OUTPUT    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Normalize repo name
      run: |
        echo "OWN_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV      
    - name: Build and push Docker image frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ env.OWN_LOWER }}/${{ env.REPO_NAME }}:front-${{ steps.git-version.outputs.VERSION }}
    - name: Build and push Docker image backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ env.OWN_LOWER }}/${{ env.REPO_NAME }}:backend-${{ steps.git-version.outputs.VERSION }}
    outputs:
      frontend_tag: ghcr.io/${{ env.OWN_LOWER }}/${{ env.REPO_NAME }}:front-${{ steps.git-version.outputs.VERSION }}
      backend_tag: ghcr.io/${{ env.OWN_LOWER }}/${{ env.REPO_NAME }}:backend-${{ steps.git-version.outputs.VERSION }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      FRONTEND_TAG: ${{ needs.build.outputs.frontend_tag }}
      BACKEND_TAG: ${{ needs.build.outputs.backend_tag }}
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /app/frontend
          docker-compose down
          yq -i '.services.backend.image = "${{ env.FRONTEND_TAG }}"' docker-compose.yml
          docker-compose pull
          docker-compose up -d
          cd /app/backend
          docker-compose down
          yq -i '.services.frontend.image = "${{ env.BACKEND_TAG }}"' docker-compose.yml
          docker-compose pull
          docker-compose up -d

